### PR TITLE
Update to fresh VMA & Vulkan 1.2

### PR DESCRIPTION
**Pull request by YaaZ**

### CODE REVIEW

**Comment by thesmallcreeper** [comment]
Cheers!
Started using VMA (haven't even compiled yet :P ) and the setup when using dynamic linking had changed. This PR gotta help me :)

**Review by thesmallcreeper — APPROVED** [review]
Compiled and tested basic stuff using this PR. I used dynamic linking, aka `VK_NO_PROTOTYPES`.

**Comment by malte-v** [comment]
It looks like the new VMA is a development version, but considering the last release was almost two years ago, I'm fine with that. Could you please document the new VMA version (including the git commit hash) in the README?

**Comment by malte-v** [comment]
Thanks!

**Pull request merged**
