### PR TITLE
Custom generator & Vulkan 1.3 support

### PR DESCRIPTION
**Pull request by YaaZ**
Please see the updated README for the details

### CODE REVIEW

**Comment by malte-v** [comment]
Since this basically amounts to a full rewrite, I actually don't see any reason to have it in this repo. This is entirely your work, so honestly you should host it in your own domain. I will add a notice to the README referring users to your updated (compatible) version.

**Comment by YaaZ** [comment]
I'm OK with that too. Just wanted to share this for anyone who'd need it

**Comment by YaaZ** [comment]
FYI: I updated this to a release 3.0.0 version: https://github.com/YaaZ/VulkanMemoryAllocator-Hpp

**Comment by malte-v** [comment]
I've added a link to your version to the README.

**Pull request closed without merging**
